const quarter1 = [
    { number: 1, name: "Hydrogen", symbol: "H", mass: "1.008", block: "Nonmetal", state: "Gas", melt: "13.99 K", boil: "20.271 K", density: "0.00008988 g/cm³", config: "1s1", electro: "2.20", discoverer: "Henry Cavendish", summary: "Hydrogen is a chemical element with symbol H and atomic number 1. It is the lightest and most abundant element in the universe, existing under normal conditions as a colorless, odorless, highly flammable diatomic gas. It plays a central role in stars through nuclear fusion and forms compounds like water when combined with oxygen." },
    { number: 2, name: "Helium", symbol: "He", mass: "4.0026", block: "Noble Gas", state: "Gas", melt: "0.95 K", boil: "4.222 K", density: "0.0001785 g/cm³", config: "1s2", electro: "N/A", discoverer: "Pierre Janssen, Norman Lockyer", summary: "Helium is a chemical element with symbol He and atomic number 2. It is a colorless, odorless, inert noble gas that is the second lightest and second most abundant element in the observable universe. It has the lowest boiling point of all elements and remains liquid near absolute zero." },
    { number: 3, name: "Lithium", symbol: "Li", mass: "6.94", block: "Alkali Metal", state: "Solid", melt: "453.65 K", boil: "1603 K", density: "0.534 g/cm³", config: "[He] 2s1", electro: "0.98", discoverer: "Johan August Arfwedson", summary: "Lithium is a chemical element with symbol Li and atomic number 3. It is a soft, silvery-white alkali metal that is highly reactive and flammable, and it is the lightest metal and lightest solid element. Lithium is widely used in rechargeable batteries and certain psychiatric medications." },
    { number: 4, name: "Beryllium", symbol: "Be", mass: "9.0122", block: "Alkaline Earth Metal", state: "Solid", melt: "1560 K", boil: "2742 K", density: "1.85 g/cm³", config: "[He] 2s2", electro: "1.57", discoverer: "Louis Nicolas Vauquelin", summary: "Beryllium is a chemical element with symbol Be and atomic number 4. It is a steel-gray, strong, lightweight alkaline earth metal that is relatively rare and toxic if inhaled as dust. Beryllium is prized in aerospace and X-ray equipment for its stiffness and low density." },
    { number: 5, name: "Boron", symbol: "B", mass: "10.81", block: "Metalloid", state: "Solid", melt: "2349 K", boil: "4200 K", density: "2.34 g/cm³", config: "[He] 2s2 2p1", electro: "2.04", discoverer: "Joseph Louis Gay-Lussac", summary: "Boron is a chemical element with symbol B and atomic number 5. It is a low-abundance metalloid found naturally only in compounds such as borates, and in its crystalline form it is extremely hard and a poor electrical conductor. Boron compounds are used in glassmaking, detergents, and semiconductors." },
    { number: 6, name: "Carbon", symbol: "C", mass: "12.011", block: "Nonmetal", state: "Solid", melt: "3823 K", boil: "4098 K", density: "2.267 g/cm³", config: "[He] 2s2 2p2", electro: "2.55", discoverer: "Unknown (Ancient)", summary: "Carbon is a chemical element with symbol C and atomic number 6. It is a nonmetal capable of forming an enormous variety of compounds, existing in forms ranging from soft graphite to the hardest natural material, diamond. Carbon is the chemical backbone of all known life." },
    { number: 7, name: "Nitrogen", symbol: "N", mass: "14.007", block: "Nonmetal", state: "Gas", melt: "63.15 K", boil: "77.36 K", density: "0.0012506 g/cm³", config: "[He] 2s2 2p3", electro: "3.04", discoverer: "Daniel Rutherford", summary: "Nitrogen is a chemical element with symbol N and atomic number 7. It is a colorless, odorless, largely inert diatomic gas that makes up about 78% of Earth's atmosphere. Nitrogen compounds are essential to amino acids, proteins, and fertilizers." },
    { number: 8, name: "Oxygen", symbol: "O", mass: "15.999", block: "Nonmetal", state: "Gas", melt: "54.36 K", boil: "90.20 K", density: "0.001429 g/cm³", config: "[He] 2s2 2p4", electro: "3.44", discoverer: "Carl Wilhelm Scheele, Joseph Priestley", summary: "Oxygen is a chemical element with symbol O and atomic number 8. It is a highly reactive nonmetal and a potent oxidizing agent that forms about 21% of Earth's atmosphere as a colorless, odorless diatomic gas. It is essential for cellular respiration in most living organisms." },
    { number: 9, name: "Fluorine", symbol: "F", mass: "18.998", block: "Halogen", state: "Gas", melt: "53.53 K", boil: "85.03 K", density: "0.001696 g/cm³", config: "[He] 2s2 2p5", electro: "3.98", discoverer: "Henri Moissan", summary: "Fluorine is a chemical element with symbol F and atomic number 9. It is the lightest halogen and the most electronegative and reactive of all elements, existing as a pale yellow, highly corrosive diatomic gas. Fluorine compounds are used in toothpaste, refrigerants, and industrial etching." },
    { number: 10, name: "Neon", symbol: "Ne", mass: "20.180", block: "Noble Gas", state: "Gas", melt: "24.56 K", boil: "27.07 K", density: "0.0009002 g/cm³", config: "[He] 2s2 2p6", electro: "N/A", discoverer: "William Ramsay, Morris Travers", summary: "Neon is a chemical element with symbol Ne and atomic number 10. It is a colorless, odorless noble gas that is chemically inert and famous for the reddish-orange glow it emits in electrified glass tubes. Neon is far more abundant in the universe than on Earth." },
    { number: 11, name: "Sodium", symbol: "Na", mass: "22.990", block: "Alkali Metal", state: "Solid", melt: "370.87 K", boil: "1156 K", density: "0.968 g/cm³", config: "[Ne] 3s1", electro: "0.93", discoverer: "Humphry Davy", summary: "Sodium is a chemical element with symbol Na (from Latin: natrium) and atomic number 11. It is a soft, silvery-white, highly reactive alkali metal that reacts violently with water and must be stored under oil. Sodium compounds, especially sodium chloride, are essential to biology and everyday life." },
    { number: 12, name: "Magnesium", symbol: "Mg", mass: "24.305", block: "Alkaline Earth Metal", state: "Solid", melt: "923 K", boil: "1363 K", density: "1.738 g/cm³", config: "[Ne] 3s2", electro: "1.31", discoverer: "Joseph Black", summary: "Magnesium is a chemical element with symbol Mg and atomic number 12. It is a lightweight, silvery-white alkaline earth metal that burns with a brilliant white flame and is widely alloyed for strength-to-weight applications. Magnesium is also vital to plant chlorophyll and human enzyme function." },
    { number: 13, name: "Aluminium", symbol: "Al", mass: "26.982", block: "Post-Transition Metal", state: "Solid", melt: "933.47 K", boil: "2792 K", density: "2.70 g/cm³", config: "[Ne] 3s2 3p1", electro: "1.61", discoverer: "Hans Christian Ørsted", summary: "Aluminium is a chemical element with symbol Al and atomic number 13. It is a lightweight, silvery, corrosion-resistant post-transition metal that is the most abundant metal in Earth's crust. Its low density and durability make it valuable in packaging, construction, and aerospace." },
    { number: 14, name: "Silicon", symbol: "Si", mass: "28.085", block: "Metalloid", state: "Solid", melt: "1687 K", boil: "3538 K", density: "2.329 g/cm³", config: "[Ne] 3s2 3p2", electro: "1.90", discoverer: "Jöns Jacob Berzelius", summary: "Silicon is a chemical element with symbol Si and atomic number 14. It is a hard, brittle metalloid with a blue-gray metallic luster that is the second most abundant element in Earth's crust after oxygen. Silicon's semiconducting properties make it the foundation of modern electronics." },
    { number: 15, name: "Phosphorus", symbol: "P", mass: "30.974", block: "Nonmetal", state: "Solid", melt: "317.3 K", boil: "553.6 K", density: "1.823 g/cm³", config: "[Ne] 3s2 3p3", electro: "2.19", discoverer: "Hennig Brand", summary: "Phosphorus is a chemical element with symbol P and atomic number 15. It exists in several allotropes, most notably a waxy white form that glows faintly in air and a more stable red form. Phosphorus is essential to DNA, RNA, and energy-carrying molecules like ATP in living cells." },
    { number: 16, name: "Sulfur", symbol: "S", mass: "32.06", block: "Nonmetal", state: "Solid", melt: "388.36 K", boil: "717.8 K", density: "2.07 g/cm³", config: "[Ne] 3s2 3p4", electro: "2.58", discoverer: "Unknown (Ancient)", summary: "Sulfur is a chemical element with symbol S and atomic number 16. It is a bright yellow, brittle nonmetal that occurs naturally in volcanic regions and forms a wide range of compounds, many with distinctive odors. Sulfur is essential for amino acids and is widely used in fertilizers and vulcanized rubber." },
    { number: 17, name: "Chlorine", symbol: "Cl", mass: "35.45", block: "Halogen", state: "Gas", melt: "171.6 K", boil: "239.11 K", density: "0.003214 g/cm³", config: "[Ne] 3s2 3p5", electro: "3.16", discoverer: "Carl Wilhelm Scheele", summary: "Chlorine is a chemical element with symbol Cl and atomic number 17. It is a pale yellow-green, highly reactive halogen gas with a sharp, suffocating odor that is toxic in concentrated form. Chlorine compounds are widely used for disinfecting water and manufacturing plastics." },
    { number: 18, name: "Argon", symbol: "Ar", mass: "39.948", block: "Noble Gas", state: "Gas", melt: "83.80 K", boil: "87.30 K", density: "0.001784 g/cm³", config: "[Ne] 3s2 3p6", electro: "N/A", discoverer: "Lord Rayleigh, William Ramsay", summary: "Argon is a chemical element with symbol Ar and atomic number 18. It is a colorless, odorless noble gas that is chemically inert and makes up about 1% of Earth's atmosphere, the most abundant noble gas there. Argon is commonly used to provide an unreactive atmosphere for welding and lightbulbs." },
    { number: 19, name: "Potassium", symbol: "K", mass: "39.098", block: "Alkali Metal", state: "Solid", melt: "336.53 K", boil: "1032 K", density: "0.89 g/cm³", config: "[Ar] 4s1", electro: "0.82", discoverer: "Humphry Davy", summary: "Potassium is a chemical element with symbol K (from Neo-Latin: kalium) and atomic number 19. It is a soft, silvery-white alkali metal that reacts vigorously with water and is never found free in nature. Potassium ions are essential for nerve function and are widely used in fertilizers." },
    { number: 20, name: "Calcium", symbol: "Ca", mass: "40.078", block: "Alkaline Earth Metal", state: "Solid", melt: "1115 K", boil: "1757 K", density: "1.55 g/cm³", config: "[Ar] 4s2", electro: "1.00", discoverer: "Humphry Davy", summary: "Calcium is a chemical element with symbol Ca and atomic number 20. It is a soft, gray alkaline earth metal that is the fifth most abundant element in Earth's crust and a key structural component of bones and shells. Calcium reacts readily with water and air, so it is not found free in nature." },
    { number: 21, name: "Scandium", symbol: "Sc", mass: "44.956", block: "Transition Metal", state: "Solid", melt: "1814 K", boil: "3109 K", density: "2.985 g/cm³", config: "[Ar] 3d1 4s2", electro: "1.36", discoverer: "Lars Fredrik Nilson", summary: "Scandium is a chemical element with symbol Sc and atomic number 21. It is a soft, silvery-white transition metal that is relatively rare and often classified alongside the rare earth elements due to its similar chemistry. Scandium is used in aerospace alloys and high-intensity lighting." },
    { number: 22, name: "Titanium", symbol: "Ti", mass: "47.867", block: "Transition Metal", state: "Solid", melt: "1941 K", boil: "3560 K", density: "4.506 g/cm³", config: "[Ar] 3d2 4s2", electro: "1.54", discoverer: "William Gregor", summary: "Titanium is a chemical element with symbol Ti and atomic number 22. It is a lustrous, silvery transition metal prized for its high strength-to-weight ratio and excellent resistance to corrosion, including in seawater. Titanium alloys are widely used in aerospace, medical implants, and sporting goods." },
    { number: 23, name: "Vanadium", symbol: "V", mass: "50.942", block: "Transition Metal", state: "Solid", melt: "2183 K", boil: "3680 K", density: "6.00 g/cm³", config: "[Ar] 3d3 4s2", electro: "1.63", discoverer: "Andrés Manuel del Río", summary: "Vanadium is a chemical element with symbol V and atomic number 23. It is a hard, silvery-gray transition metal that is naturally found in about 65 different minerals and forms a protective oxide layer when exposed to air. Vanadium is primarily used to strengthen steel alloys." },
    { number: 24, name: "Chromium", symbol: "Cr", mass: "51.996", block: "Transition Metal", state: "Solid", melt: "2180 K", boil: "2944 K", density: "7.19 g/cm³", config: "[Ar] 3d5 4s1", electro: "1.66", discoverer: "Louis Nicolas Vauquelin", summary: "Chromium is a chemical element with symbol Cr and atomic number 24. It is a hard, lustrous, steel-gray transition metal highly resistant to tarnishing, known for its use in shiny decorative plating and stainless steel. Chromium compounds can display a wide range of vivid colors." },
    { number: 25, name: "Manganese", symbol: "Mn", mass: "54.938", block: "Transition Metal", state: "Solid", melt: "1519 K", boil: "2334 K", density: "7.21 g/cm³", config: "[Ar] 3d5 4s2", electro: "1.55", discoverer: "Johan Gottlieb Gahn", summary: "Manganese is a chemical element with symbol Mn and atomic number 25. It is a hard, brittle, silvery-gray transition metal that is essential in trace amounts for many biological processes and widely used to strengthen and desulfurize steel. It does not occur as a free element in nature." },
    { number: 26, name: "Iron", symbol: "Fe", mass: "55.845", block: "Transition Metal", state: "Solid", melt: "1811 K", boil: "3134 K", density: "7.874 g/cm³", config: "[Ar] 3d6 4s2", electro: "1.83", discoverer: "Unknown (Ancient)", summary: "Iron is a chemical element with symbol Fe (from Latin: ferrum) and atomic number 26. It is a lustrous, silvery-gray transition metal and the most common element on Earth by mass, forming much of the planet's core. Iron is foundational to steelmaking and is vital to oxygen transport in blood via hemoglobin." },
    { number: 27, name: "Cobalt", symbol: "Co", mass: "58.933", block: "Transition Metal", state: "Solid", melt: "1768 K", boil: "3200 K", density: "8.90 g/cm³", config: "[Ar] 3d7 4s2", electro: "1.88", discoverer: "Georg Brandt", summary: "Cobalt is a chemical element with symbol Co and atomic number 27. It is a hard, lustrous, silvery-blue transition metal that is ferromagnetic and often found alongside nickel and copper ores. Cobalt is a key component of rechargeable battery cathodes and durable metal alloys." },
    { number: 28, name: "Nickel", symbol: "Ni", mass: "58.693", block: "Transition Metal", state: "Solid", melt: "1728 K", boil: "3186 K", density: "8.908 g/cm³", config: "[Ar] 3d8 4s2", electro: "1.91", discoverer: "Axel Fredrik Cronstedt", summary: "Nickel is a chemical element with symbol Ni and atomic number 28. It is a hard, silvery-white, ferromagnetic transition metal known for its corrosion resistance and is a major component of stainless steel. Nickel is also used extensively in coinage and rechargeable batteries." },
    { number: 29, name: "Copper", symbol: "Cu", mass: "63.546", block: "Transition Metal", state: "Solid", melt: "1357.77 K", boil: "2835 K", density: "8.96 g/cm³", config: "[Ar] 3d10 4s1", electro: "1.90", discoverer: "Unknown (Ancient)", summary: "Copper is a chemical element with symbol Cu (from Latin: cuprum) and atomic number 29. It is a soft, malleable, reddish-orange transition metal with excellent electrical and thermal conductivity, second only to silver. Copper has been used by humans for thousands of years in tools, wiring, and alloys like bronze and brass." },
    { number: 30, name: "Zinc", symbol: "Zn", mass: "65.38", block: "Transition Metal", state: "Solid", melt: "692.68 K", boil: "1180 K", density: "7.14 g/cm³", config: "[Ar] 3d10 4s2", electro: "1.65", discoverer: "Unknown (Ancient)", summary: "Zinc is a chemical element with symbol Zn and atomic number 30. It is a bluish-white, brittle transition metal that is commonly used to galvanize steel and protect it from rusting. Zinc is also an essential trace mineral for human enzyme function and immune health." }
];

const quarter2 = [
    { number: 31, name: "Gallium", symbol: "Ga", mass: "69.723", block: "Post-Transition Metal", state: "Solid", melt: "302.91 K", boil: "2477 K", density: "5.91 g/cm³", config: "[Ar] 3d10 4s2 3p1", electro: "1.81", discoverer: "Lecoq de Boisbaudran", summary: "Gallium is a chemical element with symbol Ga and atomic number 31. It is a soft, silvery post-transition metal notable for melting near room temperature, allowing it to liquefy in the palm of a hand. Gallium is widely used in semiconductors and LED technology." },
    { number: 32, name: "Germanium", symbol: "Ge", mass: "72.63", block: "Metalloid", state: "Solid", melt: "1211.40 K", boil: "3106 K", density: "5.323 g/cm³", config: "[Ar] 3d10 4s2 4p2", electro: "2.01", discoverer: "Clemens Winkler", summary: "Germanium is a chemical element with symbol Ge and atomic number 32. It is a hard, grayish-white metalloid that behaves as a semiconductor and was historically important in early transistor technology. Today it is used in fiber optics, infrared optics, and solar cells." },
    { number: 33, name: "Arsenic", symbol: "As", mass: "74.921", block: "Metalloid", state: "Solid", melt: "1090 K", boil: "887 K", density: "5.727 g/cm³", config: "[Ar] 3d10 4s2 4p3", electro: "2.18", discoverer: "Albertus Magnus", summary: "Arsenic is a chemical element with symbol As and atomic number 33. It is a notoriously toxic metalloid that commonly exists as a brittle, steel-gray solid and has been historically infamous as a poison. Arsenic compounds are used in semiconductors, pesticides, and wood preservatives." },
    { number: 34, name: "Selenium", symbol: "Se", mass: "78.971", block: "Nonmetal", state: "Solid", melt: "494 K", boil: "958 K", density: "4.81 g/cm³", config: "[Ar] 3d10 4s2 4p4", electro: "2.55", discoverer: "Jöns Jakob Berzelius", summary: "Selenium is a chemical element with symbol Se and atomic number 34. It is a nonmetal that exhibits photoconductive and photovoltaic properties, existing in several allotropes including a red and a gray metallic form. Selenium is an essential trace nutrient and is used in glassmaking and photocopiers." },
    { number: 35, name: "Bromine", symbol: "Br", mass: "79.904", block: "Halogen", state: "Liquid", melt: "265.8 K", boil: "332.0 K", density: "3.1028 g/cm³", config: "[Ar] 3d10 4s2 4p5", electro: "2.96", discoverer: "Antoine Jérôme Balard", summary: "Bromine is a chemical element with symbol Br and atomic number 35. It is a reddish-brown, corrosive liquid halogen at room temperature with a strong, unpleasant odor, one of only two elements liquid at standard conditions. Bromine compounds are used in flame retardants and water treatment." },
    { number: 36, name: "Krypton", symbol: "Kr", mass: "83.798", block: "Noble Gas", state: "Gas", melt: "115.79 K", boil: "119.93 K", density: "0.003749 g/cm³", config: "[Ar] 3d10 4s2 4p6", electro: "3.00", discoverer: "William Ramsay, Morris Travers", summary: "Krypton is a chemical element with symbol Kr and atomic number 36. It is a colorless, odorless noble gas that is extremely rare in Earth's atmosphere and largely chemically inert. Krypton is used in certain high-performance lighting and photographic flashes." },
    { number: 37, name: "Rubidium", symbol: "Rb", mass: "85.467", block: "Alkali Metal", state: "Solid", melt: "312.46 K", boil: "961 K", density: "1.532 g/cm³", config: "[Kr] 5s1", electro: "0.82", discoverer: "Robert Bunsen, Gustav Kirchhoff", summary: "Rubidium is a chemical element with symbol Rb and atomic number 37. It is a soft, silvery-white alkali metal that is highly reactive, ignites spontaneously in air, and reacts violently with water. Rubidium is used in specialized atomic clocks and research applications." },
    { number: 38, name: "Strontium", symbol: "Sr", mass: "87.62", block: "Alkaline Earth Metal", state: "Solid", melt: "1050 K", boil: "1655 K", density: "2.63 g/cm³", config: "[Kr] 5s2", electro: "0.95", discoverer: "Adair Crawford", summary: "Strontium is a chemical element with symbol Sr and atomic number 38. It is a soft, silvery alkaline earth metal that rapidly develops a yellowish tint when exposed to air and burns with a brilliant red flame. Strontium compounds are used in fireworks and some ceramic magnets." },
    { number: 39, name: "Yttrium", symbol: "Y", mass: "88.905", block: "Transition Metal", state: "Solid", melt: "1799 K", boil: "3609 K", density: "4.472 g/cm³", config: "[Kr] 4d1 5s2", electro: "1.22", discoverer: "Johan Gadolin", summary: "Yttrium is a chemical element with symbol Y and atomic number 39. It is a silvery, moderately soft transition metal often grouped chemically with the rare earth elements. Yttrium is used in LED phosphors, camera lenses, and superconductors." },
    { number: 40, name: "Zirconium", symbol: "Zr", mass: "91.224", block: "Transition Metal", state: "Solid", melt: "2128 K", boil: "4682 K", density: "6.52 g/cm³", config: "[Kr] 4d2 5s2", electro: "1.33", discoverer: "Martin Heinrich Klaproth", summary: "Zirconium is a chemical element with symbol Zr and atomic number 40. It is a lustrous, grayish-white transition metal highly resistant to corrosion, especially from acids and seawater. Zirconium alloys are used in nuclear reactors and its oxide forms brilliant cubic zirconia gemstones." },
    { number: 41, name: "Niobium", symbol: "Nb", mass: "92.906", block: "Transition Metal", state: "Solid", melt: "2750 K", boil: "5017 K", density: "8.57 g/cm³", config: "[Kr] 4d4 5s1", electro: "1.6", discoverer: "Charles Hatchett", summary: "Niobium is a chemical element with symbol Nb and atomic number 41. It is a soft, ductile, gray transition metal that becomes superconducting at low temperatures and is often used in specialized steel alloys. Niobium is also a popular material for hypoallergenic jewelry." },
    { number: 42, name: "Molybdenum", symbol: "Mo", mass: "95.95", block: "Transition Metal", state: "Solid", melt: "2896 K", boil: "4912 K", density: "10.28 g/cm³", config: "[Kr] 4d5 5s1", electro: "2.16", discoverer: "Carl Wilhelm Scheele", summary: "Molybdenum is a chemical element with symbol Mo and atomic number 42. It is a hard, silvery transition metal with one of the highest melting points of all elements, making it valuable in high-strength steel alloys. Molybdenum is also an essential trace element for many enzymes." },
    { number: 43, name: "Technetium", symbol: "Tc", mass: "98", block: "Transition Metal", state: "Solid", melt: "2430 K", boil: "4538 K", density: "11.5 g/cm³", config: "[Kr] 4d5 5s2", electro: "1.9", discoverer: "Emilio Segrè, Carlo Perrier", summary: "Technetium is a chemical element with symbol Tc and atomic number 43. It is a silvery-gray radioactive transition metal notable as the lightest element with no stable isotopes, and it was the first element to be artificially produced. Technetium-99m is widely used in medical diagnostic imaging." },
    { number: 44, name: "Ruthenium", symbol: "Ru", mass: "101.07", block: "Transition Metal", state: "Solid", melt: "2607 K", boil: "4423 K", density: "12.37 g/cm³", config: "[Kr] 4d7 5s1", electro: "2.2", discoverer: "Karl Ernst Claus", summary: "Ruthenium is a chemical element with symbol Ru and atomic number 44. It is a rare, hard, silvery-white transition metal belonging to the platinum group, prized for hardening platinum and palladium alloys. Ruthenium compounds are also used as catalysts and in electronics." },
    { number: 45, name: "Rhodium", symbol: "Rh", mass: "102.91", block: "Transition Metal", state: "Solid", melt: "2237 K", boil: "3968 K", density: "12.45 g/cm³", config: "[Kr] 4d8 5s1", electro: "2.28", discoverer: "William Hyde Wollaston", summary: "Rhodium is a chemical element with symbol Rh and atomic number 45. It is a rare, hard, silvery-white transition metal from the platinum group known for its extremely high reflectivity and corrosion resistance. Rhodium is prominently used in catalytic converters and jewelry plating." },
    { number: 46, name: "Palladium", symbol: "Pd", mass: "106.42", block: "Transition Metal", state: "Solid", melt: "1828.05 K", boil: "3236 K", density: "12.023 g/cm³", config: "[Kr] 4d10", electro: "2.20", discoverer: "William Hyde Wollaston", summary: "Palladium is a chemical element with symbol Pd and atomic number 46. It is a rare, lustrous, silvery-white platinum-group metal notable for its ability to absorb large volumes of hydrogen gas. Palladium is a key catalyst in automotive exhaust systems and electronics." },
    { number: 47, name: "Silver", symbol: "Ag", mass: "107.87", block: "Transition Metal", state: "Solid", melt: "1234.93 K", boil: "2435 K", density: "10.49 g/cm³", config: "[Kr] 4d10 5s1", electro: "1.93", discoverer: "Unknown (Ancient)", summary: "Silver is a chemical element with symbol Ag (from Latin: argentum) and atomic number 47. It is a soft, lustrous, white transition metal that possesses the highest electrical and thermal conductivity of any element. Silver has long been valued for jewelry, currency, and its antibacterial properties." },
    { number: 48, name: "Cadmium", symbol: "Cd", mass: "112.41", block: "Transition Metal", state: "Solid", melt: "594.22 K", boil: "1040 K", density: "8.65 g/cm³", config: "[Kr] 4d10 5s2", electro: "1.69", discoverer: "Friedrich Stromeyer", summary: "Cadmium is a chemical element with symbol Cd and atomic number 48. It is a soft, bluish-white, toxic transition metal chemically similar to zinc, historically used in pigments and rechargeable nickel-cadmium batteries. Its toxicity has led to increasingly restricted use." },
    { number: 49, name: "Indium", symbol: "In", mass: "114.82", block: "Post-Transition Metal", state: "Solid", melt: "429.75 K", boil: "2345 K", density: "7.31 g/cm³", config: "[Kr] 4d10 5s2 5p1", electro: "1.78", discoverer: "Ferdinand Reich, Hieronymous Theodor Richter", summary: "Indium is a chemical element with symbol In and atomic number 49. It is a soft, silvery-white post-transition metal known for its extreme malleability and low melting point relative to other metals. Indium is essential to touchscreen and flat-panel display technology via indium tin oxide." },
    { number: 50, name: "Tin", symbol: "Sn", mass: "118.71", block: "Post-Transition Metal", state: "Solid", melt: "505.08 K", boil: "2875 K", density: "7.265 g/cm³", config: "[Kr] 4d10 5s2 5p2", electro: "1.96", discoverer: "Unknown (Ancient)", summary: "Tin is a chemical element with symbol Sn (from Latin: stannum) and atomic number 50. It is a soft, silvery, malleable post-transition metal highly resistant to corrosion, historically alloyed with copper to form bronze. Tin is still widely used today in solder and protective plating." },
    { number: 51, name: "Antimony", symbol: "Sb", mass: "121.76", block: "Metalloid", state: "Solid", melt: "903.78 K", boil: "1860 K", density: "6.697 g/cm³", config: "[Kr] 4d10 5s2 5p3", electro: "2.05", discoverer: "Unknown (Ancient)", summary: "Antimony is a chemical element with symbol Sb (from Latin: stibium) and atomic number 51. It is a brittle, silvery-white metalloid known since ancient times, often alloyed to increase the hardness of lead. Antimony compounds are used in flame retardants and semiconductors." },
    { number: 52, name: "Tellurium", symbol: "Te", mass: "127.60", block: "Metalloid", state: "Solid", melt: "722.66 K", boil: "1261 K", density: "6.24 g/cm³", config: "[Kr] 4d10 5s2 5p4", electro: "2.1", discoverer: "Franz-Joseph Müller von Reichenstein", summary: "Tellurium is a chemical element with symbol Te and atomic number 52. It is a brittle, silvery-white metalloid that is chemically related to selenium and sulfur, and one of the rarest stable elements on Earth. Tellurium is used in solar panels and to strengthen certain metal alloys." },
    { number: 53, name: "Iodine", symbol: "I", mass: "126.90", block: "Halogen", state: "Solid", melt: "386.85 K", boil: "457.4 K", density: "4.933 g/cm³", config: "[Kr] 4d10 5s2 5p5", electro: "2.66", discoverer: "Bernard Courtois", summary: "Iodine is a chemical element with symbol I and atomic number 53. It is the heaviest stable halogen, existing as lustrous, dark violet-black crystals that sublime directly into a purple vapor. Iodine is an essential trace nutrient required for thyroid hormone production." },
    { number: 54, name: "Xenon", symbol: "Xe", mass: "131.29", block: "Noble Gas", state: "Gas", melt: "161.4 K", boil: "165.03 K", density: "0.005894 g/cm³", config: "[Kr] 4d10 5s2 5p6", electro: "2.6", discoverer: "William Ramsay, Morris Travers", summary: "Xenon is a chemical element with symbol Xe and atomic number 54. It is a colorless, dense, odorless noble gas that, unlike lighter noble gases, can form a limited number of chemical compounds under certain conditions. Xenon is used in specialized lighting and as an anesthetic in some medical settings." },
    { number: 55, name: "Cesium", symbol: "Cs", mass: "132.91", block: "Alkali Metal", state: "Solid", melt: "301.59 K", boil: "944 K", density: "1.93 g/cm³", config: "[Xe] 6s1", electro: "0.79", discoverer: "Robert Bunsen, Gustav Kirchhoff", summary: "Cesium is a chemical element with symbol Cs and atomic number 55. It is a soft, gold-colored alkali metal that is one of only a few metals liquid near room temperature and reacts explosively with water. Cesium-133 defines the international standard for the second in atomic clocks." },
    { number: 56, name: "Barium", symbol: "Ba", mass: "137.33", block: "Alkaline Earth Metal", state: "Solid", melt: "1000 K", boil: "2170 K", density: "3.51 g/cm³", config: "[Xe] 6s2", electro: "0.89", discoverer: "Humphry Davy", summary: "Barium is a chemical element with symbol Ba and atomic number 56. It is a soft, silvery alkaline earth metal that is highly reactive and never found free in nature due to its reactivity with air and water. Barium sulfate is used as a contrast agent in medical imaging." },
    { number: 57, name: "Lanthanum", symbol: "La", mass: "138.91", block: "Lanthanide", state: "Solid", melt: "1193 K", boil: "3737 K", density: "6.146 g/cm³", config: "[Xe] 5d1 6s2", electro: "1.1", discoverer: "Carl Gustaf Mosander", summary: "Lanthanum is a chemical element with symbol La and atomic number 57. It is a soft, silvery-white metal and the first element of the lanthanide series, reactive enough to tarnish quickly in air. Lanthanum compounds are used in camera lenses, catalysts, and rechargeable batteries." },
    { number: 58, name: "Cerium", symbol: "Ce", mass: "140.12", block: "Lanthanide", state: "Solid", melt: "1068 K", boil: "3716 K", density: "6.689 g/cm³", config: "[Xe] 4f1 5d1 6s2", electro: "1.12", discoverer: "J. Berzelius, W. von Hisinger, M. Klaproth", summary: "Cerium is a chemical element with symbol Ce and atomic number 58. It is a soft, silvery, reactive metal and the most abundant of the rare earth elements. Cerium compounds are used in catalytic converters, glass polishing, and lighter flints." },
    { number: 59, name: "Praseodymium", symbol: "Pr", mass: "140.91", block: "Lanthanide", state: "Solid", melt: "1208 K", boil: "3793 K", density: "6.64 g/cm³", config: "[Xe] 4f3 6s2", electro: "1.13", discoverer: "Carl Auer von Welsbach", summary: "Praseodymium is a chemical element with symbol Pr and atomic number 59. It is a soft, silvery, malleable rare earth metal that develops a green tarnish when exposed to air. Praseodymium is used to color glass and ceramics and to strengthen magnesium alloys." },
    { number: 60, name: "Neodymium", symbol: "Nd", mass: "144.24", block: "Lanthanide", state: "Solid", melt: "1297 K", boil: "3347 K", density: "7.01 g/cm³", config: "[Xe] 4f4 6s2", electro: "1.14", discoverer: "Carl Auer von Welsbach", summary: "Neodymium is a chemical element with symbol Nd and atomic number 60. It is a bright, silvery rare earth metal best known as a key component of extremely powerful permanent magnets. Neodymium magnets are widely used in headphones, motors, and hard drives." }
];

const quarter3 = [
    { number: 61, name: "Promethium", symbol: "Pm", mass: "145", block: "Lanthanide", state: "Solid", melt: "1315 K", boil: "3273 K", density: "7.26 g/cm³", config: "[Xe] 4f5 6s2", electro: "1.13", discoverer: "Chien Shiung Wu et al.", summary: "Promethium is a chemical element with symbol Pm and atomic number 61. It is a radioactive rare earth metal with no stable isotopes, making it one of only two such elements lighter than bismuth. Promethium is used in small nuclear-powered batteries and luminous paints." },
    { number: 62, name: "Samarium", symbol: "Sm", mass: "150.36", block: "Lanthanide", state: "Solid", melt: "1345 K", boil: "2067 K", density: "7.52 g/cm³", config: "[Xe] 4f6 6s2", electro: "1.17", discoverer: "Lecoq de Boisbaudran", summary: "Samarium is a chemical element with symbol Sm and atomic number 62. It is a moderately hard, silvery rare earth metal used together with cobalt to make powerful, heat-resistant permanent magnets. Samarium is also used in some cancer treatments and nuclear reactor control rods." },
    { number: 63, name: "Europium", symbol: "Eu", mass: "151.96", block: "Lanthanide", state: "Solid", melt: "1099 K", boil: "1802 K", density: "5.244 g/cm³", config: "[Xe] 4f7 6s2", electro: "1.2", discoverer: "Eugène-Anatole Demarçay", summary: "Europium is a chemical element with symbol Eu and atomic number 63. It is the most reactive of the rare earth metals and is best known for the vivid red and blue phosphors it produces in display and lighting technology. Europium compounds are also used as anti-counterfeiting markers on banknotes." },
    { number: 64, name: "Gadolinium", symbol: "Gd", mass: "157.25", block: "Lanthanide", state: "Solid", melt: "1585 K", boil: "3546 K", density: "7.90 g/cm³", config: "[Xe] 4f7 5d1 6s2", electro: "1.2", discoverer: "Jean Charles Galissard de Marignac", summary: "Gadolinium is a chemical element with symbol Gd and atomic number 64. It is a silvery-white rare earth metal that is strongly paramagnetic and forms compounds widely used as contrast agents in MRI scans. Gadolinium also has notable applications in nuclear reactor shielding." },
    { number: 65, name: "Terbium", symbol: "Tb", mass: "158.93", block: "Lanthanide", state: "Solid", melt: "1629 K", boil: "3503 K", density: "8.23 g/cm³", config: "[Xe] 4f9 6s2", electro: "1.2", discoverer: "Carl Gustaf Mosander", summary: "Terbium is a chemical element with symbol Tb and atomic number 65. It is a silvery-white, malleable rare earth metal that is relatively soft and ductile enough to be cut with a knife. Terbium is used in green phosphors for displays and in solid-state devices." },
    { number: 66, name: "Dysprosium", symbol: "Dy", mass: "162.50", block: "Lanthanide", state: "Solid", melt: "1680 K", boil: "2840 K", density: "8.540 g/cm³", config: "[Xe] 4f10 6s2", electro: "1.22", discoverer: "Lecoq de Boisbaudran", summary: "Dysprosium is a chemical element with symbol Dy and atomic number 66. It is a soft, silvery rare earth metal that retains high magnetic susceptibility even at low temperatures. Dysprosium is added to neodymium magnets to improve their performance at high temperatures." },
    { number: 67, name: "Holmium", symbol: "Ho", mass: "164.93", block: "Lanthanide", state: "Solid", melt: "1734 K", boil: "2993 K", density: "8.79 g/cm³", config: "[Xe] 4f11 6s2", electro: "1.23", discoverer: "Marc Delafontaine, Jacques-Louis Soret", summary: "Holmium is a chemical element with symbol Ho and atomic number 67. It is a relatively soft, silvery rare earth metal that possesses the highest magnetic strength of any naturally occurring element. Holmium is used in some nuclear control rods and medical lasers." },
    { number: 68, name: "Erbium", symbol: "Er", mass: "167.26", block: "Lanthanide", state: "Solid", melt: "1802 K", boil: "3141 K", density: "9.066 g/cm³", config: "[Xe] 4f12 6s2", electro: "1.24", discoverer: "Carl Gustaf Mosander", summary: "Erbium is a chemical element with symbol Er and atomic number 68. It is a silvery-white rare earth metal best known for its use in erbium-doped fiber amplifiers that boost signals in optical communication networks. Erbium compounds also give a pink tint to certain glasses and gemstones." },
    { number: 69, name: "Thulium", symbol: "Tm", mass: "168.93", block: "Lanthanide", state: "Solid", melt: "1818 K", boil: "2223 K", density: "9.32 g/cm³", config: "[Xe] 4f13 6s2", electro: "1.25", discoverer: "Per Teodor Cleve", summary: "Thulium is a chemical element with symbol Tm and atomic number 69. It is the least abundant of the naturally occurring rare earth elements, a soft, silvery-gray metal with limited commercial use. Thulium is used in some portable X-ray devices and specialized lasers." },
    { number: 70, name: "Ytterbium", symbol: "Yb", mass: "173.05", block: "Lanthanide", state: "Solid", melt: "1097 K", boil: "1469 K", density: "6.90 g/cm³", config: "[Xe] 4f14 6s2", electro: "1.1", discoverer: "Jean Charles Galissard de Marignac", summary: "Ytterbium is a chemical element with symbol Yb and atomic number 70. It is a soft, silvery rare earth metal notable for its use in atomic clocks that rival the precision of cesium standards. Ytterbium is also used in certain fiber lasers and stress gauges." },
    { number: 71, name: "Lutetium", symbol: "Lu", mass: "174.97", block: "Lanthanide", state: "Solid", melt: "1925 K", boil: "3675 K", density: "9.841 g/cm³", config: "[Xe] 4f14 5d1 6s2", electro: "1.27", discoverer: "Georges Urbain, Carl Auer von Welsbach", summary: "Lutetium is a chemical element with symbol Lu and atomic number 71. It is a silvery-white metal and the hardest and densest of the rare earth elements, typically the final element listed in the lanthanide series. Lutetium compounds are used in PET scan detectors and petroleum refining catalysts." },
    { number: 72, name: "Hafnium", symbol: "Hf", mass: "178.49", block: "Transition Metal", state: "Solid", melt: "2506 K", boil: "4876 K", density: "13.31 g/cm³", config: "[Xe] 4f14 5d2 6s2", electro: "1.3", discoverer: "Dirk Coster, George de Hevesy", summary: "Hafnium is a chemical element with symbol Hf and atomic number 72. It is a lustrous, silvery, corrosion-resistant transition metal chemically similar to zirconium and often found alongside it in nature. Hafnium is used in nuclear control rods and advanced computer chip components." },
    { number: 73, name: "Tantalum", symbol: "Ta", mass: "180.95", block: "Transition Metal", state: "Solid", melt: "3290 K", boil: "5731 K", density: "16.69 g/cm³", config: "[Xe] 4f14 5d3 6s2", electro: "1.5", discoverer: "Anders Gustaf Ekeberg", summary: "Tantalum is a chemical element with symbol Ta and atomic number 73. It is a dense, hard, blue-gray transition metal highly resistant to corrosion by acids, making it valuable for chemical equipment. Tantalum is a critical material in the tiny capacitors found in modern electronics." },
    { number: 74, name: "Tungsten", symbol: "W", mass: "183.84", block: "Transition Metal", state: "Solid", melt: "3695 K", boil: "5828 K", density: "19.25 g/cm³", config: "[Xe] 4f14 5d4 6s2", electro: "2.36", discoverer: "Fausto and Juan José de Elhuyar", summary: "Tungsten is a chemical element with symbol W (from German: wolfram) and atomic number 74. It is a very dense, steel-gray metal that has the highest melting point of all metals. Tungsten's hardness and heat resistance make it ideal for light bulb filaments and cutting tools." },
    { number: 75, name: "Rhenium", symbol: "Re", mass: "186.21", block: "Transition Metal", state: "Solid", melt: "3459 K", boil: "5869 K", density: "21.02 g/cm³", config: "[Xe] 4f14 5d5 6s2", electro: "1.9", discoverer: "Walter Noddack, Ida Tacke, Otto Berg", summary: "Rhenium is a chemical element with symbol Re and atomic number 75. It is one of the rarest elements in Earth's crust, a dense, silvery-white transition metal with an extremely high melting point second only to tungsten and carbon. Rhenium is used in high-temperature superalloys for jet engines." },
    { number: 76, name: "Osmium", symbol: "Os", mass: "190.23", block: "Transition Metal", state: "Solid", melt: "3306 K", boil: "5285 K", density: "22.61 g/cm³", config: "[Xe] 4f14 5d6 6s2", electro: "2.2", discoverer: "Smithson Tennant", summary: "Osmium is a chemical element with symbol Os and atomic number 76. It is a hard, brittle, bluish-white transition metal that is the densest naturally occurring element. Osmium is typically alloyed with other platinum-group metals for use in fountain pen tips and electrical contacts." },
    { number: 77, name: "Iridium", symbol: "Ir", mass: "192.22", block: "Transition Metal", state: "Solid", melt: "2719 K", boil: "4701 K", density: "22.65 g/cm³", config: "[Xe] 4f14 5d7 6s2", electro: "2.2", discoverer: "Smithson Tennant", summary: "Iridium is a chemical element with symbol Ir and atomic number 77. It is a hard, brittle, silvery-white transition metal and one of the most corrosion-resistant metals known, even at high temperatures. Iridium is used in spark plugs, crucibles, and the international prototype standards for mass and length." },
    { number: 78, name: "Platinum", symbol: "Pt", mass: "195.08", block: "Transition Metal", state: "Solid", melt: "2041.4 K", boil: "4098 K", density: "21.09 g/cm³", config: "[Xe] 4f14 5d9 6s1", electro: "2.28", discoverer: "Antonio de Ulloa", summary: "Platinum is a chemical element with symbol Pt and atomic number 78. It is a dense, malleable, silvery-white precious metal highly resistant to corrosion and tarnish, making it prized in jewelry and laboratory equipment. Platinum is also a critical catalyst in catalytic converters and fuel cells." },
    { number: 79, name: "Gold", symbol: "Au", mass: "196.97", block: "Transition Metal", state: "Solid", melt: "1337.33 K", boil: "3129 K", density: "19.30 g/cm³", config: "[Xe] 4f14 5d10 6s1", electro: "2.54", discoverer: "Unknown (Ancient)", summary: "Gold is a chemical element with symbol Au (from Latin: aurum) and atomic number 79. In its purest form, it is a bright, slightly reddish yellow, dense, soft, malleable and ductile metal. Chemically, gold is a transition metal and a group 11 element." },
    { number: 80, name: "Mercury", symbol: "Hg", mass: "200.59", block: "Transition Metal", state: "Liquid", melt: "234.32 K", boil: "629.88 K", density: "13.534 g/cm³", config: "[Xe] 4f14 5d10 6s2", electro: "2.00", discoverer: "Unknown (Ancient)", summary: "Mercury is a chemical element with symbol Hg (from Latin: hydrargyrum) and atomic number 80. It is a heavy, silvery transition metal that is the only metal known to be liquid at standard room temperature. Mercury has been used historically in thermometers and industrial processes, though its toxicity has sharply limited modern use." },
    { number: 81, name: "Thallium", symbol: "Tl", mass: "204.38", block: "Post-Transition Metal", state: "Solid", melt: "577 K", boil: "1746 K", density: "11.85 g/cm³", config: "[Xe] 4f14 5d10 6s2 6p1", electro: "1.62", discoverer: "William Crookes", summary: "Thallium is a chemical element with symbol Tl and atomic number 81. It is a soft, gray post-transition metal that resembles lead in appearance but tarnishes quickly in air. Thallium and its compounds are highly toxic and were once notoriously used as a poison." },
    { number: 82, name: "Lead", symbol: "Pb", mass: "207.2", block: "Post-Transition Metal", state: "Solid", melt: "600.61 K", boil: "2022 K", density: "11.34 g/cm³", config: "[Xe] 4f14 5d10 6s2 6p2", electro: "1.87", discoverer: "Unknown (Ancient)", summary: "Lead is a chemical element with symbol Pb (from Latin: plumbum) and atomic number 82. It is a heavy, soft, malleable post-transition metal with a bluish-white color when freshly cut that quickly tarnishes to dull gray. Lead has been used for centuries in batteries, radiation shielding, and pipes, though its toxicity has curtailed many former uses." },
    { number: 83, name: "Bismuth", symbol: "Bi", mass: "208.98", block: "Post-Transition Metal", state: "Solid", melt: "544.7 K", boil: "1837 K", density: "9.78 g/cm³", config: "[Xe] 4f14 5d10 6s2 6p3", electro: "2.02", discoverer: "Unknown (Ancient)", summary: "Bismuth is a chemical element with symbol Bi and atomic number 83. It is a brittle, silvery-white metal often exhibiting a distinctive pinkish tinge and colorful, rainbow-hued oxide surface. Bismuth is one of the least toxic heavy metals and is used in cosmetics, pharmaceuticals, and low-melting alloys." },
    { number: 84, name: "Polonium", symbol: "Po", mass: "209", block: "Metalloid", state: "Solid", melt: "527 K", boil: "1235 K", density: "9.196 g/cm³", config: "[Xe] 4f14 5d10 6s2 6p4", electro: "2.0", discoverer: "Marie Curie, Pierre Curie", summary: "Polonium is a chemical element with symbol Po and atomic number 84. It is a rare, highly radioactive metalloid first discovered by Marie and Pierre Curie and named after Poland. Due to its intense radioactivity, polonium has limited use, primarily in specialized static eliminators and heat sources." },
    { number: 85, name: "Astatine", symbol: "At", mass: "210", block: "Halogen", state: "Solid", melt: "575 K", boil: "610 K", density: "N/A", config: "[Xe] 4f14 5d10 6s2 6p5", electro: "2.2", discoverer: "Dale R. Corson, Kenneth Ross MacKenzie, Emilio Segrè", summary: "Astatine is a chemical element with symbol At and atomic number 85. It is an extremely rare, highly radioactive halogen believed to be the rarest naturally occurring element in Earth's crust. Its intense radioactivity makes it difficult to study, though it holds potential in targeted cancer therapy." },
    { number: 86, name: "Radon", symbol: "Rn", mass: "222", block: "Noble Gas", state: "Gas", melt: "202 K", boil: "211.3 K", density: "0.00973 g/cm³", config: "[Xe] 4f14 5d10 6s2 6p6", electro: "N/A", discoverer: "Friedrich Ernst Dorn", summary: "Radon is a chemical element with symbol Rn and atomic number 86. It is a colorless, odorless, radioactive noble gas produced by the natural decay of uranium and thorium in rocks and soil. Radon exposure indoors is a recognized health hazard and a leading cause of lung cancer among nonsmokers." },
    { number: 87, name: "Francium", symbol: "Fr", mass: "223", block: "Alkali Metal", state: "Solid", melt: "300 K", boil: "950 K", density: "1.87 g/cm³", config: "[Rn] 7s1", electro: "0.7", discoverer: "Marguerite Perey", summary: "Francium is a chemical element with symbol Fr and atomic number 87. It is an extremely rare and highly radioactive alkali metal with an extraordinarily short half-life, making it one of the least stable naturally occurring elements. Francium exists in such minute quantities that its physical and chemical properties are not directly observable." },
    { number: 88, name: "Radium", symbol: "Ra", mass: "226", block: "Alkaline Earth Metal", state: "Solid", melt: "973 K", boil: "2010 K", density: "5.5 g/cm³", config: "[Rn] 7s2", electro: "0.9", discoverer: "Marie Curie, Pierre Curie", summary: "Radium is a chemical element with symbol Ra and atomic number 88. It is a highly radioactive, silvery-white alkaline earth metal that glows faintly blue-green due to its intense radioactivity. Once used in luminous paints and early cancer treatments, its hazards have led to strict handling controls today." },
    { number: 89, name: "Actinium", symbol: "Ac", mass: "227", block: "Actinide", state: "Solid", melt: "1323 K", boil: "3471 K", density: "10.07 g/cm³", config: "[Rn] 6d1 7s2", electro: "1.1", discoverer: "André-Louis Debierne", summary: "Actinium is a chemical element with symbol Ac and atomic number 89. It is a soft, silvery radioactive metal that glows faintly blue in the dark due to the intense radiation it emits. Actinium gives its name to the actinide series and has limited use in research and targeted radiotherapy." },
    { number: 90, name: "Thorium", symbol: "Th", mass: "232.04", block: "Actinide", state: "Solid", melt: "2023 K", boil: "5061 K", density: "11.72 g/cm³", config: "[Rn] 6d2 7s2", electro: "1.3", discoverer: "Jöns Jakob Berzelius", summary: "Thorium is a chemical element with symbol Th and atomic number 90. It is a silvery, radioactive actinide metal that tarnishes to black over time and is roughly three times more abundant than uranium in Earth's crust. Thorium is being explored as a potential alternative nuclear fuel." }
];

const quarter4 = [
    { number: 91, name: "Protactinium", symbol: "Pa", mass: "231.04", block: "Actinide", state: "Solid", melt: "1841 K", boil: "4300 K", density: "15.37 g/cm³", config: "[Rn] 5f2 6d1 7s2", electro: "1.5", discoverer: "Oswald Helmuth Göring, Kasimir Fajans", summary: "Protactinium is a chemical element with symbol Pa and atomic number 91. It is a dense, silvery, highly radioactive actinide metal that is rare and difficult to isolate due to its scarcity and radioactivity. Protactinium has few practical applications outside of scientific research." },
    { number: 92, name: "Uranium", symbol: "U", mass: "238.03", block: "Actinide", state: "Solid", melt: "1405.3 K", boil: "4404 K", density: "19.1 g/cm³", config: "[Rn] 5f3 6d1 7s2", electro: "1.38", discoverer: "Martin Heinrich Klaproth", summary: "Uranium is a chemical element with symbol U and atomic number 92. It is a dense, silvery-gray radioactive actinide metal that is the heaviest naturally occurring element found in significant quantities on Earth. Uranium is best known as the primary fuel for nuclear power plants and weapons." },
    { number: 93, name: "Neptunium", symbol: "Np", mass: "237", block: "Actinide", state: "Solid", melt: "912 K", boil: "4273 K", density: "20.45 g/cm³", config: "[Rn] 5f4 6d1 7s2", electro: "1.36", discoverer: "Edwin McMillan, Philip H. Abelson", summary: "Neptunium is a chemical element with symbol Np and atomic number 93. It is a silvery, radioactive actinide metal and the first of the transuranium elements, meaning it lies beyond uranium on the periodic table. Neptunium is primarily produced as a byproduct of nuclear reactors." },
    { number: 94, name: "Plutonium", symbol: "Pu", mass: "244", block: "Actinide", state: "Solid", melt: "912.5 K", boil: "3501 K", density: "19.816 g/cm³", config: "[Rn] 5f6 7s2", electro: "1.28", discoverer: "Glenn T. Seaborg et al.", summary: "Plutonium is a chemical element with symbol Pu and atomic number 94. It is a silvery, radioactive actinide metal that tarnishes when exposed to air and is capable of sustaining a nuclear chain reaction. Plutonium is a key material in nuclear weapons and certain types of nuclear reactors." },
    { number: 95, name: "Americium", symbol: "Am", mass: "243", block: "Actinide", state: "Solid", melt: "1449 K", boil: "2880 K", density: "12.0 g/cm³", config: "[Rn] 5f7 7s2", electro: "1.13", discoverer: "Glenn T. Seaborg et al.", summary: "Americium is a chemical element with symbol Am and atomic number 95. It is a silvery, radioactive actinide metal that does not occur naturally and was first produced during early nuclear research. Americium is best known for its use in household smoke detectors." },
    { number: 96, name: "Curium", symbol: "Cm", mass: "247", block: "Actinide", state: "Solid", melt: "1613 K", boil: "3383 K", density: "13.51 g/cm³", config: "[Rn] 5f7 6d1 7s2", electro: "1.28", discoverer: "Glenn T. Seaborg et al.", summary: "Curium is a chemical element with symbol Cm and atomic number 96. It is a silvery, radioactive actinide metal named in honor of Marie and Pierre Curie, and it does not occur naturally on Earth. Curium is primarily used in scientific research and as a power source for some spacecraft instruments." },
    { number: 97, name: "Berkelium", symbol: "Bk", mass: "247", block: "Actinide", state: "Solid", melt: "1259 K", boil: "2900 K", density: "14.78 g/cm³", config: "[Rn] 5f9 7s2", electro: "1.3", discoverer: "Stanley G. Thompson et al.", summary: "Berkelium is a chemical element with symbol Bk and atomic number 97. It is a soft, silvery, radioactive actinide metal first synthesized at the University of California, Berkeley, for which it is named. Berkelium exists only in trace, laboratory-produced quantities with no commercial applications." },
    { number: 98, name: "Californium", symbol: "Cf", mass: "251", block: "Actinide", state: "Solid", melt: "1173 K", boil: "1743 K", density: "15.1 g/cm³", config: "[Rn] 5f10 7s2", electro: "1.3", discoverer: "Stanley G. Thompson et al.", summary: "Californium is a chemical element with symbol Cf and atomic number 98. It is a silvery, radioactive actinide metal notable as a strong neutron emitter, making it useful for starting up nuclear reactors and in neutron-based scanning devices. It was first synthesized at the University of California, Berkeley." },
    { number: 99, name: "Einsteinium", symbol: "Es", mass: "252", block: "Actinide", state: "Solid", melt: "1133 K", boil: "1269 K", density: "8.84 g/cm³", config: "[Rn] 5f11 7s2", electro: "1.3", discoverer: "Albert Ghiorso et al.", summary: "Einsteinium is a chemical element with symbol Es and atomic number 99. It is a silvery, highly radioactive actinide metal first identified in the debris of a thermonuclear test and named in honor of Albert Einstein. Einsteinium exists only in minute synthesized quantities used for scientific study." },
    { number: 100, name: "Fermium", symbol: "Fm", mass: "257", block: "Actinide", state: "Solid", melt: "1800 K", boil: "Unknown", density: "Unknown", config: "[Rn] 5f12 7s2", electro: "1.3", discoverer: "Albert Ghiorso et al.", summary: "Fermium is a chemical element with symbol Fm and atomic number 100. It is a radioactive actinide metal first discovered in nuclear test debris and named after physicist Enrico Fermi. Fermium has no practical applications and is produced only in trace amounts for research." },
    { number: 101, name: "Mendelevium", symbol: "Md", mass: "258", block: "Actinide", state: "Solid", melt: "1100 K", boil: "Unknown", density: "Unknown", config: "[Rn] 5f13 7s2", electro: "1.3", discoverer: "Albert Ghiorso et al.", summary: "Mendelevium is a chemical element with symbol Md and atomic number 101. It is a radioactive synthetic element named after Dmitri Mendeleev, the creator of the periodic table. Mendelevium can only be produced in particle accelerators, one atom at a time." },
    { number: 102, name: "Nobelium", symbol: "No", mass: "259", block: "Actinide", state: "Solid", melt: "1100 K", boil: "Unknown", density: "Unknown", config: "[Rn] 5f14 7s2", electro: "1.3", discoverer: "Albert Ghiorso et al.", summary: "Nobelium is a chemical element with symbol No and atomic number 102. It is a radioactive synthetic actinide named after Alfred Nobel, and its properties are known only from studying tiny numbers of atoms. Nobelium has no practical uses outside of basic scientific research." },
    { number: 103, name: "Lawrencium", symbol: "Lr", mass: "266", block: "Actinide", state: "Solid", melt: "1900 K", boil: "Unknown", density: "Unknown", config: "[Rn] 5f14 7s2 7p1", electro: "1.3", discoverer: "Albert Ghiorso et al.", summary: "Lawrencium is a chemical element with symbol Lr and atomic number 103. It is a synthetic, highly radioactive element named after physicist Ernest Lawrence and marks the final member of the actinide series. Lawrencium can only be created briefly in laboratory particle accelerators." },
    { number: 104, name: "Rutherfordium", symbol: "Rf", mass: "267", block: "Transition Metal", state: "Solid", melt: "2400 K", boil: "5800 K", density: "23.2 g/cm³", config: "[Rn] 5f14 6d2 7s2", electro: "Unknown", discoverer: "JINR / LBNL", summary: "Rutherfordium is a chemical element with symbol Rf and atomic number 104. It is a synthetic, highly radioactive transactinide element named after physicist Ernest Rutherford and marks the beginning of period 7's transition metals. Only a few atoms of rutherfordium have ever been produced." },
    { number: 105, name: "Dubnium", symbol: "Db", mass: "268", block: "Transition Metal", state: "Solid", melt: "Unknown", boil: "Unknown", density: "29.3 g/cm³", config: "[Rn] 5f14 6d3 7s2", electro: "Unknown", discoverer: "JINR / LBNL", summary: "Dubnium is a chemical element with symbol Db and atomic number 105. It is a synthetic, highly radioactive transition metal named after the Joint Institute for Nuclear Research in Dubna, Russia. Dubnium exists only fleetingly in laboratory settings and has no practical applications." },
    { number: 106, name: "Seaborgium", symbol: "Sg", mass: "269", block: "Transition Metal", state: "Solid", melt: "Unknown", boil: "Unknown", density: "35.0 g/cm³", config: "[Rn] 5f14 6d4 7s2", electro: "Unknown", discoverer: "Albert Ghiorso et al.", summary: "Seaborgium is a chemical element with symbol Sg and atomic number 106. It is a synthetic, highly radioactive transactinide element named in honor of chemist Glenn T. Seaborg. It can only be produced in minute quantities using particle accelerators." },
    { number: 107, name: "Bohrium", symbol: "Bh", mass: "270", block: "Transition Metal", state: "Solid", melt: "Unknown", boil: "Unknown", density: "37.1 g/cm³", config: "[Rn] 5f14 6d5 7s2", electro: "Unknown", discoverer: "GSI Helmholtz Centre", summary: "Bohrium is a chemical element with symbol Bh and atomic number 107. It is a synthetic, extremely radioactive transactinide element named after physicist Niels Bohr. Bohrium has an extremely short half-life and no known applications beyond research." },
    { number: 108, name: "Hassium", symbol: "Hs", mass: "277", block: "Transition Metal", state: "Solid", melt: "Unknown", boil: "Unknown", density: "40.7 g/cm³", config: "[Rn] 5f14 6d6 7s2", electro: "Unknown", discoverer: "GSI Helmholtz Centre", summary: "Hassium is a chemical element with symbol Hs and atomic number 108. It is a synthetic, highly radioactive transactinide element named after the German state of Hesse, where it was first synthesized. Hassium decays within fractions of a second of being created." },
    { number: 109, name: "Meitnerium", symbol: "Mt", mass: "278", block: "Transition Metal", state: "Solid", melt: "Unknown", boil: "Unknown", density: "37.4 g/cm³", config: "[Rn] 5f14 6d7 7s2", electro: "Unknown", discoverer: "GSI Helmholtz Centre", summary: "Meitnerium is a chemical element with symbol Mt and atomic number 109. It is a synthetic, extremely radioactive transactinide element named after physicist Lise Meitner. Only a handful of meitnerium atoms have ever been detected." },
    { number: 110, name: "Darmstadtium", symbol: "Ds", mass: "281", block: "Transition Metal", state: "Solid", melt: "Unknown", boil: "Unknown", density: "34.8 g/cm³", config: "[Rn] 5f14 6d8 7s2", electro: "Unknown", discoverer: "GSI Helmholtz Centre", summary: "Darmstadtium is a chemical element with symbol Ds and atomic number 110. It is a synthetic, highly radioactive transactinide element named after Darmstadt, Germany, where it was first created. It decays almost instantly and exists only in laboratory conditions." },
    { number: 111, name: "Roentgenium", symbol: "Rg", mass: "282", block: "Transition Metal", state: "Solid", melt: "Unknown", boil: "Unknown", density: "28.7 g/cm³", config: "[Rn] 5f14 6d9 7s2", electro: "Unknown", discoverer: "GSI Helmholtz Centre", summary: "Roentgenium is a chemical element with symbol Rg and atomic number 111. It is a synthetic, extremely radioactive transactinide element named after physicist Wilhelm Röntgen, discoverer of X-rays. It has an exceptionally short half-life and no practical applications." },
    { number: 112, name: "Copernicium", symbol: "Cn", mass: "285", block: "Transition Metal", state: "Liquid (predicted)", melt: "Unknown", boil: "Unknown", density: "23.7 g/cm³", config: "[Rn] 5f14 6d10 7s2", electro: "Unknown", discoverer: "GSI Helmholtz Centre", summary: "Copernicium is a chemical element with symbol Cn and atomic number 112. It is a synthetic, highly radioactive transactinide element named after astronomer Nicolaus Copernicus. Predicted to behave like a heavy, possibly liquid or gaseous, metal, it decays almost immediately after creation." },
    { number: 113, name: "Nihonium", symbol: "Nh", mass: "286", block: "Post-Transition Metal", state: "Solid", melt: "Unknown", boil: "Unknown", density: "16 g/cm³", config: "[Rn] 5f14 6d10 7s2 7p1", electro: "Unknown", discoverer: "RIKEN", summary: "Nihonium is a chemical element with symbol Nh and atomic number 113. It is a synthetic, highly radioactive superheavy element named after Japan (Nihon), where it was first confirmed. Nihonium decays within a fraction of a second and has no known practical use." },
    { number: 114, name: "Flerovium", symbol: "Fl", mass: "289", block: "Post-Transition Metal", state: "Gas (predicted)", melt: "Unknown", boil: "Unknown", density: "14 g/cm³", config: "[Rn] 5f14 6d10 7s2 7p2", electro: "Unknown", discoverer: "JINR", summary: "Flerovium is a chemical element with symbol Fl and atomic number 114. It is a synthetic, highly radioactive superheavy element named after the Flerov Laboratory of Nuclear Reactions in Russia. It is predicted to behave as an unusually volatile metal, possibly gaseous at room temperature." },
    { number: 115, name: "Moscovium", symbol: "Mc", mass: "290", block: "Post-Transition Metal", state: "Solid", melt: "Unknown", boil: "Unknown", density: "13.5 g/cm³", config: "[Rn] 5f14 6d10 7s2 7p3", electro: "Unknown", discoverer: "JINR / LLNL", summary: "Moscovium is a chemical element with symbol Mc and atomic number 115. It is a synthetic, highly radioactive superheavy element named after the Moscow region, where it was first synthesized. Moscovium exists for only fractions of a second before decaying." },
    { number: 116, name: "Livermorium", symbol: "Lv", mass: "293", block: "Post-Transition Metal", state: "Solid", melt: "Unknown", boil: "Unknown", density: "12.9 g/cm³", config: "[Rn] 5f14 6d10 7s2 7p4", electro: "Unknown", discoverer: "JINR / LLNL", summary: "Livermorium is a chemical element with symbol Lv and atomic number 116. It is a synthetic, highly radioactive superheavy element named after the Lawrence Livermore National Laboratory in California. It decays almost instantly and is produced only in extremely limited quantities." },
    { number: 117, name: "Tennessine", symbol: "Ts", mass: "294", block: "Halogen", state: "Solid", melt: "Unknown", boil: "Unknown", density: "7.1 g/cm³", config: "[Rn] 5f14 6d10 7s2 7p5", electro: "Unknown", discoverer: "JINR / LLNL / ORNL", summary: "Tennessine is a chemical element with symbol Ts and atomic number 117. It is a synthetic, highly radioactive superheavy element named after the U.S. state of Tennessee, home to research institutions involved in its discovery. Tennessine is predicted to be a halogen with unusual, more metallic properties than its lighter relatives." },
    { number: 118, name: "Oganesson", symbol: "Og", mass: "294", block: "Noble Gas", state: "Gas (predicted)", melt: "Unknown", boil: "Unknown", density: "5 g/cm³", config: "[Rn] 5f14 6d10 7s2 7p6", electro: "Unknown", discoverer: "JINR / LLNL", summary: "Oganesson is a chemical element with symbol Og and atomic number 118. It is a synthetic, highly radioactive superheavy element and the heaviest element to have been synthesized, named after physicist Yuri Oganessian. Though classified under the noble gases, it is theorized to behave quite differently due to relativistic effects." }
];

// Combine all the arrays together into one massive list!
const allElements = [...quarter1, ...quarter2, ...quarter3, ...quarter4];

// The actual bot command export
module.exports = {
    name: "element",
    alias: ["elements", "periodic"],
    category: "Info",
    desc: "Search for a periodic table element by name, symbol, or atomic number.",
    execute: async (bot, m, { args, reply }) => {
        if (!args.length) {
            return reply("Please provide an element name, symbol, or atomic number to search for!");
        }

        const query = args.join(" ").toLowerCase();

        // Find the element in our combined array
        const data = allElements.find(
            (e) => e.name.toLowerCase() === query ||
                   e.symbol.toLowerCase() === query ||
                   e.number.toString() === query
        );

        if (!data) {
            return reply("I couldn't find that element! Please check your spelling.");
        }

        const row = (label, value) => `│ ${label.padEnd(18)}: ${value || 'N/A'}\n`;
        let caption = `╭─❍ *CODEX AI PERIODIC TABLE*\n`;
        caption += `│ *${data.name}* (${data.symbol}) • Atomic No. ${data.number}\n`;
        caption += `├────────────────────\n`;
        caption += row('Atomic mass', data.mass);
        caption += row('Block', data.block);
        caption += row('State', data.state);
        caption += row('Bonding', data.bonding);
        caption += row('Melting point', data.melt);
        caption += row('Boiling point', data.boil);
        caption += row('Density', data.density);
        caption += row('Electron config', data.config);
        caption += row('Oxidation states', data.oxidation);
        caption += row('Electronegativity', data.electro);
        caption += row('Electron affinity', data.affinity);
        caption += row('Ionization energy', data.ionization);
        caption += row('Atomic radius', data.radius);
        caption += row('Ion radius', data.ionRadius);
        caption += row('Van der Waals', data.vdwRadius);
        caption += row('Magnetic type', data.magnetic);
        caption += row('Discovered', data.year);
        caption += row('Discoverer', data.discoverer);
        caption += `├────────────────────\n│ *Summary*\n│ ${data.summary || 'N/A'}\n╰─❍ CODEX AI`;

        await m.reply(caption);
        await bot.sendMessage(m.chat, { react: { text: '⚛️', key: m.key } }).catch(() => {});
    }
};
