
const fs = require('fs');
const path = require('path');

module.exports = {
    name: 'chart',
    aliases: ['graph', 'plot', 'bargraph'],
    category: 'documents',
    reactions: { start: '⚙️' },
    description: 'Generate an ASCII bar chart and export as a .txt file.',

    async execute(bot, m, args) {
        const prefix = bot.prefix || '.';
        const input = args.join(' ').trim();
        
        if (!input) {
            return await m.reply(`Usage: ${prefix}chart Title | label1:value1 | label2:value2\nExample: ${prefix}chart Sales | Jan:100 | Feb:250 | Mar:180`);
        }

        const parts = input.split('|').map(p => p.trim());
        if (parts.length < 2) {
            return await m.reply(`❌ Please provide a title and at least one data point.\nExample: ${prefix}chart Sales | Jan:100 | Feb:250`);
        }

        const title = parts[0];
        let maxVal = 0;
        const data = [];

        parts.slice(1).forEach(p => {
            const match = p.match(/^(.+):(\d+)$/);
            if (match) {
                const val = parseInt(match[2], 10);
                data.push({ label: match[1].trim(), value: val });
                if (val > maxVal) maxVal = val;
            }
        });

        if (!data.length) {
            return await m.reply('❌ No valid data found. Make sure your data points use the `Label:Value` format.');
        }

        const barWidth = 20;
        
        // Find the longest label to ensure perfect vertical alignment
        const maxLabelLength = Math.max(...data.map(d => d.label.length), 8);
        
        let chart = `${title.toUpperCase()}\n${'═'.repeat(40 + maxLabelLength - 8)}\n`;

        data.forEach(d => {
            // Prevent division by zero if all values are 0
            const fill = maxVal > 0 ? Math.round((d.value / maxVal) * barWidth) : 0;
            const bar = '█'.repeat(fill) + '░'.repeat(barWidth - fill);
            chart += `${d.label.padEnd(maxLabelLength)} │${bar} ${d.value}\n`;
        });

        chart += `${'═'.repeat(40 + maxLabelLength - 8)}\nGenerated by CODEX AI`;

        try {
            await m.reply('📊 Generating ASCII chart...');

            // Create temp directory in the root folder if it doesn't exist
            const tempDir = path.join(process.cwd(), 'temp');
            if (!fs.existsSync(tempDir)) {
                fs.mkdirSync(tempDir, { recursive: true });
            }
            
            const filePath = path.join(tempDir, `chart_${Date.now()}.txt`);
            fs.writeFileSync(filePath, chart);

            // Clean the title for a safe filename
            const safeTitle = title.replace(/[^a-zA-Z0-9]/g, '_');

            await bot.sendMessage(m.chat, {
                document: fs.readFileSync(filePath),
                fileName: `${safeTitle}_chart.txt`,
                mimetype: 'text/plain',
                caption: `*📊 ASCII CHART GENERATED*\n\n*Title:* ${title}`
            }, { quoted: m });

            // Clean up the temp file after sending
            fs.unlinkSync(filePath);

        } catch (err) {
            console.error('[CHART ERROR]', err.message);
            await m.reply('❌ Failed to generate the chart document. Please try again later.');
        }
    }
};
                                      
