
const fs = require('fs');
const path = require('path');

module.exports = {
    name: 'html',
    aliases: ['tohtml', 'text2html', 'webpage'],
    category: 'documents',
    reactions: { start: '⚙️' },
    description: 'Convert text to a simple .html document.',

    async execute(bot, m, args) {
        const prefix = bot.prefix || '.';
        let text = args.join(' ').trim();

        // Fallback to quoted message text
        if (!text && m.quoted) {
            text = (m.quoted.text || m.quoted.caption || m.quoted.body || '').trim();
        }

        if (!text) {
            return await m.reply(`Usage: ${prefix}html <text>\nOr reply to text with: ${prefix}html`);
        }

        // Limit length (HTML can handle a lot, but safety first)
        if (text.length > 15000) {
            text = text.substring(0, 14997) + '...';
        }

        try {
            await m.reply('📄 Creating HTML document...');

            // Basic HTML template with styling
            const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CODEX Text Document</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #f8f9fa;
            color: #333;
            margin: 0;
            padding: 40px;
            line-height: 1.6;
        }
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 4px 20px rgba(0,0,0,0.1);
        }
        h1 {
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
            text-align: center;
        }
        pre {
            background: #f1f1f1;
            padding: 15px;
            border-radius: 8px;
            white-space: pre-wrap; /* Ensures long text wraps to the next line */
            word-wrap: break-word;
        }
        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 0.9em;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>CODEX AI Text Document</h1>
        <pre>${text.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</pre>
        <div class="footer">
            Generated by CODEX AI • ${new Date().toLocaleString('en-NG')}
        </div>
    </div>
</body>
</html>`;

            // Create temp directory in the root folder if it doesn't exist
            const tempDir = path.join(process.cwd(), 'temp');
            if (!fs.existsSync(tempDir)) {
                fs.mkdirSync(tempDir, { recursive: true });
            }

            const fileName = `document_${Date.now()}.html`;
            const filePath = path.join(tempDir, fileName);

            fs.writeFileSync(filePath, htmlContent);

            await bot.sendMessage(m.chat, {
                document: fs.readFileSync(filePath),
                mimetype: 'text/html',
                fileName: fileName,
                caption: `*📄 HTML DOCUMENT CREATED*\n\n*Text length:* ${text.length} characters`
            }, { quoted: m });

            // Cleanup the temp file after sending
            fs.unlinkSync(filePath);

        } catch (err) {
            console.error('[HTML ERROR]', err.message);
            await m.reply('❌ Failed to create HTML document. Please try again later.');
        }
    }
};
