
module.exports = {
    name: 'table',
    aliases: ['tbl', 'grid'],
    category: 'documents',
    reactions: { start: '⚙️' },
    description: 'Generate a native table in chat.',

    async execute(bot, m, args) {
        const prefix = bot.prefix || '.';
        const input = args.join(' ').trim();
        
        if (!input) {
            return await m.reply(`Usage: ${prefix}table Title | H1,H2,H3 | R1C1,R1C2,R1C3\nExample: ${prefix}table Students | Name,Age,Grade | John,25,A | Jane,30,B`);
        }

        const parts = input.split('|').map(p => p.trim());
        if (parts.length < 2) {
            return await m.reply(`❌ Please provide a title and at least one data row.\nExample: ${prefix}table Students | Name,Age,Grade | John,25,A`);
        }

        const title = parts[0];
        const rows = parts.slice(1);

        // Build table data for WhatsApp native table
        const tableData = [];
        
        rows.forEach(row => {
            const cols = row.split(',').map(c => c.trim());
            tableData.push(cols);
        });

        try {
            await bot.sendMessage(m.chat, {
                headerText: `*📊 ${title.toUpperCase()}*`,
                contentText: '---',
                title: `${rows.length} Row${rows.length > 1 ? 's' : ''}`,
                table: tableData,
                footerText: '💡 Generated by CODEX AI'
            }, { quoted: m });
            
        } catch (err) {
            console.error('[TABLE ERROR]', err.message);
            await m.reply('❌ Failed to generate the table. Your WhatsApp version or the bot library might not fully support this interactive format yet.');
        }
    }
};
